CREATE TABLE BANKS(
  
   BANK_ID VARCHAR(20),
   BANK_NAME VARCHAR(50),
   AREA VARCHAR(20),
   STREET VARCHAR(20),
   DISTRICT VARCHAR(20),
   
   PRIMARY KEY(BANK_ID)
);

CREATE TABLE CUSTOMER(
   
    CUSTOMER_ID VARCHAR(20),
    FNAME VARCHAR(20),
    MNAME VARCHAR(20),
    LNAME VARCHAR(20),
    AREA VARCHAR(20),
   STREET VARCHAR(20),
   DISTRICT VARCHAR(20),
   DOB DATE,
   PHONE INTEGER,

   PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE CUSTOMER_EMAIL(

  CUSTOMER_ID VARCHAR(20),
  EMAIL VARCHAR(50),
  PRIMARY KEY(CUSTOMER_ID,EMAIL),
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)

);


CREATE TABLE ACCOUNT( 
  BANK_ID VARCHAR(20),
  CUSTOMER_ID VARCHAR(20),
  ACCOUNT_ID VARCHAR(20),
  ACCOUNT_NAME VARCHAR(20),
    BALANCE NUMERIC(5,2),
    PRIMARY KEY(BANK_ID,CUSTOMER_ID,ACCOUNT_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(BANK_ID)REFERENCES BANKS(BANK_ID) 

);


CREATE TABLE CUSTOMERCARDS(
  CARD_NO INTEGER,
  BANK_ID VARCHAR(20),
  CUSTOMER_ID VARCHAR(20),
  ACCOUNT_ID VARCHAR(20),
  CARDTYPE_CODE VARCHAR(20),
  DATE_VALID_FROM DATE,
  DATE_VALID_TO DATE,

  PRIMARY KEY(CARD_NO),
    FOREIGN KEY(ACCOUNT_ID,BANK_ID,CUSTOMER_ID)REFERENCES ACCOUNT(ACCOUNT_ID,BANK_ID,CUSTOMER_ID) 
 
);


CREATE TABLE BANK_BRANCHES(

  BRANCH_ID VARCHAR(20) UNIQUE,
  BANK_ID VARCHAR(20),
  BRANCH_NAME VARCHAR(20),
    AREA VARCHAR(20),
    STREET VARCHAR(20),
    DISTRICT VARCHAR(20),

    PRIMARY KEY(BRANCH_ID,BANK_ID),
    FOREIGN KEY(BANK_ID) REFERENCES BANKS(BANK_ID)

);


CREATE TABLE ATM_MACHINES (
 
  ATM_ID VARCHAR(20),
  NEAREST_BRANCH_ID VARCHAR(20),
  AREA VARCHAR(20),
    STREET VARCHAR(20),
    DISTRICT VARCHAR(20),

  PRIMARY KEY (ATM_ID),
  FOREIGN KEY (NEAREST_BRANCH_ID) REFERENCES BANK_BRANCHES(BRANCH_ID) 


);

CREATE TABLE WITHDRAW(
  
  WITHDRAW_ID VARCHAR(20),
  ATM_ID VARCHAR(20),
  CARD_NO INTEGER,
  DATE_OF_WITHDRAWL DATE,
  TIME_OF_WITHDRAWL TIMESTAMP,
   AMOUNT INTEGER,

  PRIMARY KEY (WITHDRAW_ID,ATM_ID,CARD_NO),
  FOREIGN KEY(ATM_ID)REFERENCES ATM_MACHINES(ATM_ID),
  FOREIGN KEY(CARD_NO)REFERENCES CUSTOMERCARDS(CARD_NO)
);

CREATE TABLE ATM_MACHINE_SERVICES(
  ATM_ID VARCHAR(20),
  SERVICE_TYPE_CODE VARCHAR(20),
  SERVICE_NAME VARCHAR(20),
  PRIMARY KEY (SERVICE_TYPE_CODE,ATM_ID)

);

CREATE TABLE OTHER_TRANS(
   TRANS_ID VARCHAR(20),
  ATM_ID VARCHAR(20),
  CARD_NO INTEGER,
  DATE_OF_WITHDRAWL DATE,
  TIME_OF_WITHDRAWL TIMESTAMP,
  
   PRIMARY KEY (TRANS_ID,ATM_ID,CARD_NO),
  FOREIGN KEY(ATM_ID)REFERENCES ATM_MACHINES(ATM_ID),
  FOREIGN KEY(CARD_NO)REFERENCES CUSTOMERCARDS(CARD_NO)
  
);
